import requests
from lxml import html
import re
import email
import smtplib
from email.mime.text import MIMEText

sender_email = "your_email@gmail.com"  # TODO: Replace with your email
sender_password = "your_app_password"  # TODO: Replace with your app password

beginning = 1
end = 860

for i in range(beginning, end):
    url = f'https://www.schools.nyc.gov/schools/M{i:03d}'
    response = requests.get(url)
    tree = html.fromstring(response.content)
    elements = tree.xpath('/html/body/div[1]/main/div/div/div/div[2]/div[2]/div/div[1]/div/div/dl/dd[1]/a')
    try:
        principal = elements[0].text.split(",")[0]
        address = elements[0].get('href').split(":")[1]
        print(principal, address)
        email_text = f"""Dear {principal},
We’re the team behind Luminata Prep, a new SAT prep platform built to make test preparation more accessible, personalized, and effective — especially for public school students.
Students get instant support from an AI model on any specific question or topic along with multitudes of personalized videos tailored to how the student learns. For teachers, our dashboard provides insights into student progress, allowing for more targeted support and intervention.  
The benefits for public schools are simple:
Control – Teachers can monitor and guide student progress with precision.
Accessibility – Students don’t need a private tutor or expensive course to get quality help — they can access Luminata anytime, anywhere.
Personalization – The platform adapts to each student’s strengths, weaknesses, and learning style.
All of our practice questions are generated by a model trained on actual College Board materials, so we can deliver high-quality, topic-specific practice that reflects what students will see on the real test.
You can learn more at www.luminataprep.com. We’d love to connect and explore how Luminata could support your students and teachers — and are happy to set up a quick demo if you're interested.
Thank you for your dedication to your students.
Best,
The Luminata Founders
www.luminataprep.com
"""
        msg = MIMEText(email_text)
        msg['Subject'] = "Introducing Luminata Prep: SAT Support for Public Schools"
        msg['From'] = sender_email
        msg['To'] = address
        try:
            with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
                server.login(sender_email, sender_password)
                server.sendmail(sender_email, address, msg.as_string())
            print(f"Email sent to {address}")
        except Exception as mail_error:
            print(f"Failed to send email to {address}: {mail_error}")


    except (IndexError, ValueError) as e:
        continue

